version: '3'

services:
    postgres:
        # image: postgres:12.1
        build:
            context: ./docker/db
        container_name: collectq_db
        environment:
            POSTGRES_DATABASE: ${DATABASE}
            POSTGRES_USER: ${USERNAME}
            POSTGRES_PASSWORD: ${USERPASS}
            POSTGRES_ROOT_PASSWORD: ${ROOTPASS}
        ports:
            - '3306:3306'
        volumes:
            # 初期化よう
            - ./docker/db/db_init:/docker-entrypoint-initdb.d
            # 永続化よう
            # - ./docker/db/db_data:/var/lib/postgresql/data
        networks:
            ecs-network:
                ipv4_address: 172.30.0.2
            
    golang:
        # image: golang:1.14.2-alpine
        build:
            context: ./docker/api
        container_name: collectq_api
        ports: 
            - 8080:8080
        volumes: 
            - .:/go/src
        working_dir: /go/src/app
        tty: true
        depends_on:
            - postgres
        command: go run main.go
        networks:
            ecs-network:
                ipv4_address: 172.30.0.3
        # logging:
        #     driver: awslogs
        #     options: 
        #         awslogs-group: /ecs/collectq
        #         awslogs-region: ap-northeast-1
        #         awslogs-stream-prefix: golang

networks:
    ecs-network:
      driver: bridge
      ipam:
        driver: default
        config:
          - subnet: 172.30.0.0/24